In [1]:
import pandas as pd



rec = pd.read_csv("RAW_recipes.csv")

In [2]:
rec

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13
3,alouette potatoes,59389,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8
...,...,...,...,...,...,...,...,...,...,...,...,...
231632,zydeco soup,486161,60,227978,2012-08-29,"['ham', '60-minutes-or-less', 'time-to-make', ...","[415.2, 26.0, 34.0, 26.0, 44.0, 21.0, 15.0]",7,"['heat oil in a 4-quart dutch oven', 'add cele...",this is a delicious soup that i originally fou...,"['celery', 'onion', 'green sweet pepper', 'gar...",22
231633,zydeco spice mix,493372,5,1500678,2013-01-09,"['15-minutes-or-less', 'time-to-make', 'course...","[14.8, 0.0, 2.0, 58.0, 1.0, 0.0, 1.0]",1,['mix all ingredients together thoroughly'],this spice mix will make your taste buds dance!,"['paprika', 'salt', 'garlic powder', 'onion po...",13
231634,zydeco ya ya deviled eggs,308080,40,37779,2008-06-07,"['60-minutes-or-less', 'time-to-make', 'course...","[59.2, 6.0, 2.0, 3.0, 6.0, 5.0, 0.0]",7,"['in a bowl , combine the mashed yolks and may...","deviled eggs, cajun-style","['hard-cooked eggs', 'mayonnaise', 'dijon must...",8
231635,cookies by design cookies on a stick,298512,29,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[188.0, 11.0, 57.0, 11.0, 7.0, 21.0, 9.0]",9,['place melted butter in a large mixing bowl a...,"i've heard of the 'cookies by design' company,...","['butter', 'eagle brand condensed milk', 'ligh...",10
231636,cookies by design sugar shortbread cookies,298509,20,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[174.9, 14.0, 33.0, 4.0, 4.0, 11.0, 6.0]",5,"['whip sugar and shortening in a large bowl , ...","i've heard of the 'cookies by design' company,...","['granulated sugar', 'shortening', 'eggs', 'fl...",7

In [3]:
data_recipy = rec[["id", "name"]]
data_recipy = data_recipy[data_recipy.id < 20000]
data_recipy.reset_index(drop=True, inplace=True)
data_recipy

          id                                   name
0       5289                apple a day  milk shake
1       8559                     chinese  chop suey
2       5060                  philly  waldorf salad
3      19208                    red hot  applesauce
4      18537               wait forever  pork chops
...      ...                                    ...
10004  18813                 zucchini tofu scramble
10005  11197           zucchini with bacon   cheese
10006  18498       zucchini with sour cream topping
10007  15267                  zucchini cilantro dip
10008  16940  zurichgeschnetzeltes or diced chicken

[10009 rows x 2 columns]

In [4]:
interactions = pd.read_csv("interactions_train.csv")
interactions_keep = interactions[["user_id", "recipe_id", "rating"]]
# interactions_keep[interactions_keep["recipe_id"]<5000]
interactions_keep = interactions_keep[interactions_keep.recipe_id < 20000]
interactions_keep.reset_index(drop=True, inplace=True)
interactions_keep

          user_id  recipe_id  rating
0            2046       4684     5.0
1            2046        517     5.0
2            1773       7435     5.0
3            1773        278     4.0
4            2046       3431     5.0
...           ...        ...     ...
54487      431961      14911     5.0
54488  2001362355      17615     5.0
54489      227652      19653     5.0
54490      218535      14814     5.0
54491      400708       5123     5.0

[54492 rows x 3 columns]

In [5]:

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import ast 
from ast import literal_eval
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
# from nltk.stem.snowball import SnowballStemmer
# from nltk.stem.wordnet import WordNetLemmatizer
# from nltk.corpus import wordnet
from surprise import SVD, Reader
from surprise import Dataset
from surprise.model_selection import cross_validate

import warnings; warnings.simplefilter('ignore')



reader = Reader()
data = Dataset.load_from_df(interactions_keep[['user_id', 'recipe_id', 'rating']], reader)

svd = SVD()
cross_validate(svd, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

# trainset = data.build_full_trainset()
# svd.fit(trainset)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    1.0493  1.0469  1.0459  1.0211  1.0528  1.0432  0.0113
MAE (testset)     0.6587  0.6542  0.6599  0.6447  0.6530  0.6541  0.0054
Fit time          0.35    0.41    0.36    0.40    0.38    0.38    0.02
Test time         0.03    0.09    0.03    0.09    0.03    0.05    0.03

{'test_rmse': array([1.04929306, 1.04690664, 1.04591503, 1.0211489 , 1.05275402]),
 'test_mae': array([0.65866637, 0.65423017, 0.65991017, 0.64473959, 0.6530052 ]),
 'fit_time': (0.35341668128967285,
  0.4068608283996582,
  0.35944485664367676,
  0.3975496292114258,
  0.37676167488098145),
 'test_time': (0.028204679489135742,
  0.08673524856567383,
  0.029059886932373047,
  0.0880577564239502,
  0.029431581497192383)}

In [6]:
data_recipy = data_recipy.dropna()
# data_recipy = data_recipy.loc[-50000:]
print(data_recipy.shape)
tf = TfidfVectorizer(analyzer='word',ngram_range=(1, 2), min_df=0, stop_words='english')
tfidf_matrix = tf.fit_transform(data_recipy['name'])
tfidf_matrix.shape

(10009, 2)

(10009, 21122)

In [7]:


cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [8]:
def hybrid(user_id, recipe_id, many):

    recipe_position_in_tfifd_matrix = data_recipy[data_recipy["id"]==recipe_id].index[0]

    sim_scores = list(enumerate(cosine_sim[int(recipe_position_in_tfifd_matrix)]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:100]

    recipe_indices = [i[0] for i in sim_scores]
    
    recipes = data_recipy.iloc[recipe_indices][['name', 'id']]
    
    recipes['est'] = recipes['id'].apply(lambda x: svd.predict(user_id, x).est)
    recipes = recipes.sort_values('est', ascending=False)
    return recipes.head(many)

In [9]:
interactions_test = pd.read_csv("interactions_test.csv")
interactions_test_keep = interactions_test[["user_id", "recipe_id", "rating"]]
interactions_test_keep = interactions_test_keep[interactions_test_keep.recipe_id < 20000]
interactions_test_keep.reset_index(drop=True, inplace=True)
interactions_test_keep

     user_id  recipe_id  rating
0    1251273       3665     5.0
1     470447       8690     5.0
2    2156777      18052     5.0
3     324993       9284     5.0
4      41767      10730     5.0
..       ...        ...     ...
675   326467      18455     0.0
676    75020        399     0.0
677   225054       2105     5.0
678   169613       5048     5.0
679  1248947      14944     5.0

[680 rows x 3 columns]

In [10]:
one = interactions_keep.loc[0]
# print(data_recipy[data_recipy["id"]==one["recipe_id"]])

recipes_user_rated = interactions_keep[interactions_keep["user_id"] == one.user_id]
print(recipes_user_rated)
all_recomendations = []
for recipe in recipes_user_rated.values:
    if recipe[-1]> 3:
        results = hybrid(one["user_id"], recipe[1], 10)
        all_recomendations.append(results)

all_df = pd.concat(all_recomendations)


recnames = [data_recipy[data_recipy["id"]==x[1]].name for x in recipes_user_rated.values]

print(recnames)

all_df = all_df.sort_values('est', ascending=False)
all_df

   user_id  recipe_id  rating
0     2046       4684     5.0
1     2046        517     5.0
4     2046       3431     5.0
5     2046      13307     5.0
[3902    flank steak with lime chipotle sauce
Name: name, dtype: object, 4461    greek stuffed meatloaf
Name: name, dtype: object, 5472    leek  tomato  goat cheese pizza
Name: name, dtype: object, 6377    neiman marcus  250 chocolate chip cookies recipe
Name: name, dtype: object]

                                               name     id       est
3735  erin s pb  chocolate chip and oatmeal cookies  11390  5.000000
6414                      no bake chocolate cookies  10794  4.991039
2308           chocolate christmas cookies  no bake  15859  4.984330
7196         pistachio white chocolate chip cookies   8477  4.966481
4434                    greek death by garlic pasta  16115  4.952141
1268                        breakfast pizza squares  15414  4.935621
8334            slice   bake chocolate chip cookies  17262  4.932737
9353           toll house butterscotch chip cookies  16110  4.931802
7357                potato leek soup in bread bowls   3651  4.921115
6496              oatmeal chocolate chip cookies ii   4065  4.909646
4466                     greek style turkey burgers  13285  4.907937
7213                                    pizza getti  15125  4.907171
2291                       chocolate chip cake bars  19476  4.906240
996                best ever chocolate chip cookies  10117  4.905192
7044                         pepper steak with rice  18066  4.897137
222              another pork chops and beer recipe  14221  4.896884
4450                        greek pasta with shrimp  18720  4.888831
5971                        meatloaf shepherd s pie  13625  4.877132
1647                             carpetbagger steak  13286  4.876578
7655                        raspberry lime iced tea   9499  4.873444
8879                                   stuffed sole  14075  4.867477
8870                       stuffed mexican meatloaf   6501  4.867248
4307      goat cheese   black olive mashed potatoes  10977  4.865194
1038                          bill blass s meatloaf  13238  4.850242
1267                             breakfast pizza ii   1217  4.845582
4642                      ham steak with plum sauce  16827  4.839112
4454                             greek potato skins  14493  4.837588
7893                              rosemary meatloaf  17233  4.834005
7203                                      pizza dip  19277  4.825253
6293                   mushroom stuffed flank steak   8334  4.823330
9380                                   tomato juice  16370  4.819453
5969                        meatloaf barbecue style  17394  4.810200
1015                             beth s pizza crust  13546  4.807770
5984                  mediterranean vegetable pizza  10775  4.795148
8532          spaghetti with lime   arugula  rocket  16561  4.794102
7843     roasted marinated peppers with goat cheese  11964  4.793793
2235                                  chipotle mayo  18942  4.793362
5611                             lime cumin chicken  12404  4.788818
8746                          steak and potato soup  12712  4.788069
8309                        sirloin steak casserole  14696  4.781354

In [11]:
merged = pd.merge(interactions_test_keep, interactions_keep, on="user_id", how="left", suffixes=["_test", "_train"])
merged = merged.dropna()
merged = merged.drop_duplicates(subset=['user_id'])
merged.reset_index(drop=True, inplace=True)
print(merged)

     user_id  recipe_id_test  rating_test  recipe_id_train  rating_train
0     470447            8690          5.0           4393.0           5.0
1    2156777           18052          5.0          13303.0           5.0
2      49561           14129          0.0          17723.0           5.0
3      37215            3335          4.0          12572.0           5.0
4      58407           18687          4.0          12572.0           4.0
..       ...             ...          ...              ...           ...
499    23394            2122          4.0          17574.0           4.0
500    27720           16362          5.0           4545.0           5.0
501    71247           11019          4.0          14357.0           5.0
502     1773             649          4.0           7435.0           5.0
503    20075           11214          5.0          10374.0           5.0

[504 rows x 5 columns]

In [12]:

# in_results = 0
# for i in range(len(merged)):
#     one = merged.loc[i]
#     test_rec_id = one.recipe_id_test 
#     # print(test_rec_id)
#     print("Test result")
#     print(data_recipy[data_recipy["id"]==test_rec_id].name.values[0])

#     recipes_user_rated = interactions_keep[interactions_keep["user_id"] == one.user_id]
#     recnames = [data_recipy[data_recipy["id"]==x[1]].name.values for x in recipes_user_rated.values]
#     print("Previously graded")
#     print(*list(recnames))
#     print()
#     all_recomendations = []
#     for recipe in recipes_user_rated.values:
#         if recipe[-1]> 3:
#             results = hybrid(one["user_id"], recipe[1], 100)
#             all_recomendations.append(results)

#     all_df = pd.concat(all_recomendations)


#     # recnames = [data_recipy[data_recipy["id"]==x[1]].name for x in recipes_user_rated.values]


#     all_df = all_df.sort_values('est', ascending=False)
#     print(all_df["name"].values)
#     # found = all_df[all_df['id'].astype(str).str.contains(str(test_rec_id))]
#     # print(found)
#     # break